apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: lumora-prod
  labels:
    cost-center: Multicloud-Mavericks
data:
  FLASK_ENV: "production"
  PORT: "5000"
  LOW_STOCK_THRESHOLD: "10"
---
# Pointer to AWS Secrets Manager - Zero passwords committed to Git!
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-provider
  namespace: lumora-prod
  labels:
    cost-center: Multicloud-Mavericks
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "lumora-ecommerce-prod-secrets"
        objectType: "secretsmanager"
        jmesPath: 
          - path: "SECRET_KEY"
            objectAlias: "SECRET_KEY"
          - path: "ADMIN_PASSWORD"
            objectAlias: "ADMIN_PASSWORD"
          - path: "MONGO_INITDB_ROOT_PASSWORD"
            objectAlias: "MONGO_INITDB_ROOT_PASSWORD"
  secretObjects:
    - secretName: flask-secrets
      type: Opaque
      data:
        - objectName: SECRET_KEY
          key: SECRET_KEY
        - objectName: ADMIN_PASSWORD
          key: ADMIN_PASSWORD
        - objectName: MONGO_INITDB_ROOT_PASSWORD
          key: MONGO_INITDB_ROOT_PASSWORD