- name: Configure Jenkins server
  hosts: jenkins
  become: true
  tasks:
    - name: Install packages
      apt:
        update_cache: true
        name: [openjdk-17-jdk, docker.io, python3-pip, unzip]
        state: present
    - name: Add Jenkins repository key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
    - name: Install Jenkins
      apt:
        update_cache: true
        name: jenkins
        state: present
    - name: Enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: [docker, jenkins]
    - name: Allow Jenkins to use Docker
      user:
        name: jenkins
        groups: docker
        append: true
